// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3T_nTcwSln3gYPbalE9Y9rlKcHwv5Vek',
    appId: '1:524291198943:web:6fd064085452f11887be6a',
    messagingSenderId: '524291198943',
    projectId: 'aissa-com',
    authDomain: 'aissa-com.firebaseapp.com',
    storageBucket: 'aissa-com.firebasestorage.app',
    measurementId: 'G-MCJ0PRSQZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAe_kjtlnibkA07tB9F98GtrDM6Hg0k2o',
    appId: '1:524291198943:android:67e7c80b887e18c587be6a',
    messagingSenderId: '524291198943',
    projectId: 'aissa-com',
    storageBucket: 'aissa-com.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATKHJsTg5zlDYI5pSyUXjB9v9naNN12XY',
    appId: '1:524291198943:ios:1b624608b36c6ae587be6a',
    messagingSenderId: '524291198943',
    projectId: 'aissa-com',
    storageBucket: 'aissa-com.firebasestorage.app',
    iosBundleId: 'com.aissacom.aissaCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATKHJsTg5zlDYI5pSyUXjB9v9naNN12XY',
    appId: '1:524291198943:ios:1b624608b36c6ae587be6a',
    messagingSenderId: '524291198943',
    projectId: 'aissa-com',
    storageBucket: 'aissa-com.firebasestorage.app',
    iosBundleId: 'com.aissacom.aissaCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3T_nTcwSln3gYPbalE9Y9rlKcHwv5Vek',
    appId: '1:524291198943:web:3a348e53c6b46fb487be6a',
    messagingSenderId: '524291198943',
    projectId: 'aissa-com',
    authDomain: 'aissa-com.firebaseapp.com',
    storageBucket: 'aissa-com.firebasestorage.app',
    measurementId: 'G-T70WF28EHW',
  );
}
